server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.215.66:3306/course?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: course
    password: 666666
  redis:
    host: 47.115.215.66
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null #JSON处理时忽略非空字段
